# customTemplate="/path/to/template"

# [postgres]
# host = "localhost"
# port = "5432"
# user = "postgres"
# password = "password123"
# sslmode = "disable"
# pingcheck = true
# dbname = "mydb"
# maxIdleConn = 10
# maxOpenConn = 100

# [mysql]
# host="localhost"
# port="3306"
# user="root"
# password="mysql111"
# maxIdleConn = 2
# maxOpenConn = 2

# [app]
# debug = true
